import type { MarketGroup, MarketOverviewSnapshot, MarketInstrument } from '../data/siteSnapshotTypes';

const groupLabels: Record<MarketGroup, string> = { aShare: 'A股', hongKong: '港股', us: '美股', globalAssets: '全球资产' };
const stateLabels = { trading: '交易中', delayed: '延迟行情', close: '当日收盘', previous_close: '上一交易日收盘' };
const formatTime = (value?: string | null) => value ? new Date(value).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai', hour12: false }) : '暂无';
const sessionLabel=(item:MarketInstrument)=>!item.session?stateLabels[item.marketState]:(item.provenance==='report'?'报道快照 · ':'')+({open:'开盘快照',close:'收盘快照',reference:'参考数据'})[item.session];
const observationTime=(item?:MarketInstrument)=>item?.timestampPrecision==='date'?item.tradingDate:formatTime(item?.dataAsOf);

export function MarketOverview({ snapshot, activeGroup, onGroupChange }: { snapshot?: MarketOverviewSnapshot; activeGroup: MarketGroup; onGroupChange: (group: MarketGroup) => void }) {
  const items = snapshot?.groups[activeGroup] ?? [];
  const health = snapshot?.groupHealth[activeGroup];
  const groupDataAsOf = items.map(item => item.dataAsOf).sort().at(-1);
  const latestItem=items.find(item=>item.dataAsOf===groupDataAsOf);
  const summary=snapshot?.sessionSummary?.[activeGroup];
  const up = items.filter(item => (item.changePercent ?? 0) > 0).length;
  const down = items.filter(item => (item.changePercent ?? 0) < 0).length;
  return <>
    <section className="market-hero"><div className="market-hero-head"><div><p className="eyebrow">MARKET OVERVIEW / 市场总览</p><h1>{groupLabels[activeGroup]}概览</h1></div><span className="market-status">{health?.status === 'unavailable' ? '暂无数据' : items.length ? sessionLabel(items[0]) : '等待数据'}</span></div><div className="market-summary"><strong>{summary?.facts.length?`${summary.tradingDate} 收盘总结`:items.length ? `${items.length} 个观察项，${up} 个上涨、${down} 个下跌` : '暂无可靠市场数据'}</strong>{summary?.facts.length?summary.facts.map(fact=><p key={fact}>{fact}</p>):<p>{items.length ? '以下只描述已验证数据；没有可靠证据时不推断涨跌原因。' : health?.fallbackReason ?? '数据源尚未通过验证或本轮获取失败。'}</p>}{!!summary?.explanations.length&&<details><summary>继续看收盘解读</summary>{summary.explanations.map(explanation=><p key={explanation.newsId}>{explanation.attribution}：{explanation.text} <a href={`#/news/${encodeURIComponent(explanation.newsId)}`}>查看相关解读 →</a></p>)}{!!summary.watchItems.length&&<><h3>接下来观察</h3><ul>{summary.watchItems.map(text=><li key={text}>{text}</li>)}</ul></>}{!!summary.invalidationConditions.length&&<><h3>什么证据会改变判断</h3><ul>{summary.invalidationConditions.map(text=><li key={text}>{text}</li>)}</ul></>}</details>}</div><small>数据截至 {observationTime(latestItem)} · 状态：{health?.status ?? 'unavailable'}</small></section>

    <section aria-labelledby="market-title"><div className="section-heading"><div><p className="eyebrow">主要指数与资产</p><h2 id="market-title">大类资产表现</h2></div><span>{health?.status ?? 'unavailable'}</span></div><div className="market-tabs" aria-label="市场切换">{(Object.keys(groupLabels) as MarketGroup[]).map(group => <button key={group} type="button" aria-pressed={activeGroup === group} onClick={() => onGroupChange(group)}>{groupLabels[group]}</button>)}</div>{items.length ? <div className="market-grid">{items.map(item => { const direction = item.changePercent === undefined ? 'unknown' : item.changePercent > 0 ? 'up' : item.changePercent < 0 ? 'down' : 'flat'; return <article className="market-card" key={item.id}><div className="card-row"><span className="eyebrow">{item.symbol}</span><small>{sessionLabel(item)}</small></div><div className="market-card-body"><div className="market-quote"><h3>{item.name}</h3><strong>{item.value.toLocaleString('zh-CN')}</strong><p className={`market-change ${direction === 'up' ? 'positive' : direction === 'down' ? 'negative' : ''}`}>{direction === 'unknown' ? '涨跌幅暂无' : direction === 'up' ? '↑ 上涨' : direction === 'down' ? '↓ 下跌' : '持平'} {item.changePercent === undefined ? '—' : `${Math.abs(item.changePercent).toFixed(2)}%`}</p></div></div><small>{item.timestampPrecision === 'date' ? (item.session === 'reference' ? '参考日期：' : '交易日期：') : '数据时间：'}{observationTime(item)}{item.session && (item.marketState === 'previous_close' || item.freshness === 'delayed') && <><br />最近有效数据</>}<br />来源：<a href={item.source.url} target="_blank" rel="noreferrer">{item.source.name}</a></small></article>; })}</div> : <p className="empty-state">{health?.fallbackReason ?? '暂无可靠数据，不使用演示值补位。'}</p>}</section>
  </>;
}
