import { render,screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { webcrypto } from 'node:crypto';
import { afterEach,expect,it,vi } from 'vitest';
import { App } from '../../src/app/App';
import { reviewedFetch } from '../fixtures/reviewedFeed';
afterEach(()=>vi.unstubAllGlobals());
it('opens complete professional analysis from a dated brief card',async()=>{
 vi.stubGlobal('crypto',webcrypto);vi.stubGlobal('fetch',vi.fn(reviewedFetch));
 const user=userEvent.setup();
 render(<MemoryRouter initialEntries={['/brief']}><App/></MemoryRouter>);
 const link=await screen.findByRole('link',{name:/欧洲央行加息/});
 expect(link).toHaveAttribute('href','/news/ecb-energy-rate-hike');
 expect(screen.getByText(/不作为今日重点/)).toBeInTheDocument();
 expect(screen.getByText('今天学一个')).toBeInTheDocument();
 await user.click(link);
 expect(await screen.findByRole('heading',{name:'所以呢？'})).toBeInTheDocument();
 expect(screen.getByRole('heading',{name:'主流市场解释 · 机制参考'})).toBeInTheDocument();
});
